//! Veteran Armorsmith — "Other Soldier creatures you control get +0/+1."
//!
//! Regression coverage for the continuous static P/T anthem building block,
//! exercised across every filter axis the Oracle clause carries:
//!   - **subtype** — only Soldiers are buffed (CR 205.3m creature types),
//!   - **"Other"** — the source excludes itself,
//!   - **"you control"** — the controller filter excludes opponents (CR 109.5).
//!
//! The buff is a Layer 7c power/toughness modification generated by a static
//! ability (CR 613.4c), recomputed every layer pass (CR 611.3). This drives the
//! REAL parse → synthesis → layer pipeline (`add_creature_from_oracle` runs the
//! same `synthesize_all` path as production) and reads back the EFFECTIVE
//! post-`evaluate_layers` power/toughness — it is a runtime test, not an
//! AST-shape test.

use engine::game::layers::evaluate_layers;
use engine::game::scenario::{GameRunner, GameScenario, P0, P1};
use engine::types::ability::ContinuousModification;
use engine::types::identifiers::ObjectId;
use engine::types::phase::Phase;

const VETERAN_ARMORSMITH: &str = "Other Soldier creatures you control get +0/+1.";

/// Recompute layers and read an object's effective (post-layer) power/toughness.
fn effective_pt(runner: &mut GameRunner, id: ObjectId) -> (i32, i32) {
    runner.state_mut().layers_dirty.mark_full();
    evaluate_layers(runner.state_mut());
    let obj = &runner.state().objects[&id];
    (
        obj.power.expect("creature has power"),
        obj.toughness.expect("creature has toughness"),
    )
}

/// Structural sanity: the parsed Oracle clause must carry a single continuous
/// static whose modification grants +0/+1 (a toughness bump). This is a light
/// guard; the discriminating evidence is the runtime layer behavior below.
#[test]
fn veteran_armorsmith_parses_toughness_anthem_static() {
    let mut scenario = GameScenario::new();
    let smith = scenario
        .add_creature_from_oracle(P0, "Veteran Armorsmith", 2, 3, VETERAN_ARMORSMITH)
        .with_subtypes(vec!["Human", "Soldier"])
        .id();
    let runner = scenario.build();
    let statics = runner.state().objects[&smith].static_definitions.as_slice();
    assert!(
        statics.iter().any(|sd| {
            sd.modifications
                .iter()
                .any(|m| matches!(m, ContinuousModification::AddToughness { value: 1 }))
        }),
        "Veteran Armorsmith must carry a +0/+1 (AddToughness 1) anthem static, statics={statics:?}"
    );
}

#[test]
fn veteran_armorsmith_buffs_other_soldiers_only_you_control() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);

    // Source: a 2/3 Human Soldier carrying the anthem (built through the real
    // parse + synthesis pipeline).
    let smith = scenario
        .add_creature_from_oracle(P0, "Veteran Armorsmith", 2, 3, VETERAN_ARMORSMITH)
        .with_subtypes(vec!["Human", "Soldier"])
        .id();

    // Another Soldier you control — the +0/+1 subject.
    let ally_soldier = scenario
        .add_creature(P0, "Icatian Soldier", 1, 1)
        .with_subtypes(vec!["Human", "Soldier"])
        .id();

    // A non-Soldier you control — outside the subtype filter.
    let ally_wizard = scenario
        .add_creature(P0, "Merfolk Looter", 1, 1)
        .with_subtypes(vec!["Merfolk", "Wizard"])
        .id();

    // An opponent's Soldier — outside the "you control" filter.
    let foe_soldier = scenario
        .add_creature(P1, "Onakke Ogre", 1, 1)
        .with_subtypes(vec!["Soldier"])
        .id();

    let mut runner = scenario.build();

    // CR 613.4c: the other Soldier you control gains +0/+1 → 1/2.
    assert_eq!(
        effective_pt(&mut runner, ally_soldier),
        (1, 2),
        "another Soldier you control must get +0/+1"
    );

    // "Other" excludes the source itself — it stays at base 2/3.
    assert_eq!(
        effective_pt(&mut runner, smith),
        (2, 3),
        "Veteran Armorsmith must NOT buff itself ('Other' excludes the source)"
    );

    // CR 205.3m: a non-Soldier you control is outside the subtype filter.
    assert_eq!(
        effective_pt(&mut runner, ally_wizard),
        (1, 1),
        "a non-Soldier you control must be unaffected"
    );

    // CR 109.5: "you control" excludes the opponent's Soldier.
    assert_eq!(
        effective_pt(&mut runner, foe_soldier),
        (1, 1),
        "an opponent's Soldier must be unaffected ('you control')"
    );
}

#[test]
fn veteran_armorsmith_buff_turns_off_when_source_leaves() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);

    let smith = scenario
        .add_creature_from_oracle(P0, "Veteran Armorsmith", 2, 3, VETERAN_ARMORSMITH)
        .with_subtypes(vec!["Human", "Soldier"])
        .id();
    let ally_soldier = scenario
        .add_creature(P0, "Icatian Soldier", 1, 1)
        .with_subtypes(vec!["Human", "Soldier"])
        .id();

    let mut runner = scenario.build();
    assert_eq!(
        effective_pt(&mut runner, ally_soldier),
        (1, 2),
        "baseline: ally Soldier buffed to 1/2 while the source is present"
    );

    // Remove the anthem source from the battlefield (CR 611.3: the continuous
    // effect ends when its source leaves); the ally reverts to base 1/1.
    {
        let state = runner.state_mut();
        state.battlefield.retain(|&id| id != smith);
        state.objects.remove(&smith);
    }
    assert_eq!(
        effective_pt(&mut runner, ally_soldier),
        (1, 1),
        "ally Soldier must revert to base 1/1 once the anthem source is gone"
    );
}
